<<<<<<< HEAD
# Generated by Django 2.0.7 on 2018-07-18 17:40
=======
# Generated by Django 2.0.7 on 2018-07-18 21:07
>>>>>>> bai

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='用户名')),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=10)),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='电话号码')),
                ('cardNum', models.CharField(max_length=18, unique=True, verbose_name='身份证号')),
                ('birthday', models.DateTimeField(blank=True, null=True, verbose_name='出生年月')),
                ('alias', models.CharField(blank=True, max_length=50, null=True, verbose_name='昵称')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='邮箱')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女'), ('secrecy', '保密')], default='secrecy', max_length=6, verbose_name='性别')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
=======
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=32)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['-c_time'],
>>>>>>> bai
            },
        ),
    ]
