# Generated by Django 2.0.7 on 2018-07-20 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnt', models.IntegerField(default=1)),
                ('isSelected', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConfirmString',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=254, verbose_name='确认码')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建的时间')),
            ],
            options={
                'verbose_name': '验证码',
                'verbose_name_plural': '验证码',
                'ordering': ['-c_time'],
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_id', models.CharField(default='', max_length=50, verbose_name='商品唯一货号')),
                ('cate', models.CharField(max_length=100, verbose_name='类型')),
                ('image', models.CharField(max_length=200, verbose_name='图片路径')),
                ('price', models.CharField(max_length=10, verbose_name='市场价格')),
                ('number', models.CharField(max_length=100, verbose_name='库存数量')),
                ('title', models.CharField(max_length=100, verbose_name='商品名程')),
                ('location', models.CharField(max_length=100, verbose_name='商品产地')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'taobao',
            },
        ),
        migrations.CreateModel(
            name='ShAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=20, verbose_name='收件人')),
                ('tel', models.CharField(max_length=12, verbose_name='收件人电话')),
                ('streetName', models.TextField(default='', verbose_name='收货地址')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=32)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('has_confonfirmed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['-c_time'],
            },
        ),
        migrations.AddField(
            model_name='shaddress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.User'),
        ),
        migrations.AddField(
            model_name='confirmstring',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.User', verbose_name='关联的用户'),
        ),
        migrations.AddField(
            model_name='cart',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Goods'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.User'),
        ),
    ]
